import type { Metadata } from 'next'
import './globals.css'

import { theme } from '@/theme/theme'
import { Container, CssBaseline, ThemeProvider } from '@mui/material'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
	subsets: ['latin', 'cyrillic'],
	weight: ['300', '400', '500', '700'],
	display: 'swap',
	variable: '--font-roboto',
})

export const metadata: Metadata = {
	title: 'My App',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={roboto.variable}>
				<ThemeProvider theme={theme}>
					<CssBaseline />
					<Container maxWidth='lg'>{children}</Container>
				</ThemeProvider>
			</body>
		</html>
	)
}
